const types = {
	SUGGESTS: {
		RECIEVE: 'RECIEVE_SUGGESTS',
		ADD: 'ADD_SUGGESTS',
		REMEOVE: 'REMOVE_SUGGEST'
	},
	COMMENTS: {
		ADD: 'ADD_COMMENT',
		REMOVE: 'REMOVE_COMMENT'
	},
	LIKES: {
		INCREMENT: 'INCREMENT_LIKES',
		DECREMENT: 'DECREMENT_LIKES'
	}
};

export default types;